project_id = "orluznhdcrvnyfrjccbh"

[functions.easyjur-auth]
verify_jwt = false

[functions.easyjur-sync-publicacoes]
verify_jwt = false

[functions.importar-feriados]
verify_jwt = false

[functions.assistente-juridico]
verify_jwt = false

[functions.upload-documento]
verify_jwt = false

[functions.buscar-documentos]
verify_jwt = false